services:
  gleamin:
    image: gleamin
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=database
      - DATABASE_USER=username
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=gleamin
      - STAGE=development
    develop:
      watch:
        - action: rebuild
          path: ./src
          
        - action: rebuild
          path: ./Dockerfile
  
  database:
    image: 'postgres:latest'
    ports:
      - 5433:5433

    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gleamin
    volumes:
        - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql