# fly.toml app configuration file generated for manager-horas-extra on 2024-09-01T17:29:27-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'manager-horas-extra'
primary_region = 'scl'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = "/app/styles"
  url_prefix = "/styles"
  index_document = "index.css"
